/* global Templates */
/* Lazy object, yeah... shame on me.. */
var Templates = {};

Templates.uploadTable = "<table id=\"pre-upload-table\" class=\"striped rounded l-centered\">"
		+ "<thead class=\"l-centered\"> "
		+ "<tr class=\"l-centered\">"
		+ "<th class=\"l-centered\">Nombre Archivo</th>"
		+ "<th class=\"l-centered\">Tamaño Archivo</th>"
		+ "<th class=\"l-centered\">Tipo Archivo</th>"
		+ "<th></th>"
		+ "</tr>"
		+ "</thead>"
		+ "<tbody class=\"l-centered\">"
		+ "<%"
		+ "_.each(files, function(file, key, list) {"
		+ "%>"
		+ "<tr class=\"l-centered\" id=\"upload-<%= key %>\" data-key=\"<%= key %>\" >"
		+ "<td class=\"l-centered\"> <%= file.name %> </td>"
		+ "<td class=\"l-centered\"> ~ <%= Math.floor(file.size/1048576) %> MB </td>"
		+ "<td class=\"l-centered\"> <%= file.type %> </td>"
		+ "<td class=\"l-centered\">  "
		+ "<a href=\"#\" class=\"tiny danger btn quit\""
		+ "style=\"color: #FCFCFC\" data-id=\"<%= key %>\">"
		+ "<i class=\"icon-cancel\"></i>"
		+ "</a>"
		+ "</td>"
		+ "</tr>"
		+ "<% "
		+ "});" + "%>" + "</tbody>" + "</table>";

Templates.uploadedTempalte = "<div class=\"row\"><div class=\"default alert twelve columns\"><br/>"
		+ "<div class=\"four columns l-centered\">"
		+ "<img class=\"album-cover\" src=\"/covers/<%= album %>.jpg\" />"
		+ "</div>"
		+ "<div class=\"seven columns l-centered\">"
		+ "<h4><i class=\"icon-note\" /><%= cancion.nombre %></h4>"
		+ "<p class=\"l-centered\"><i class=\"icon-mic\" /><%= cancion.artista.nombre %></p>"
		+ "<p class=\"l-centered\"><i class=\"icon-music\" /><%= cancion.album.nombre %></p>"
		+ "<p class=\"l-centered\"><i class=\"icon-note-beamed\" /><%= cancion.genero.nombre %></p>"
		+ "</div> </article> </div></div>";

Templates.playlistSong = "<div data-id=\"<%= id %>\" class=\"song-playlist\">"
		+ "<div class=\"song-playlist-art\">"
		+ "<img class=\"song-playlist-cover\""
		+ "src=\"/covers/<%= album %>.jpg\" alt=\"\" />"
		+ "</div>"
		+ "<div class=\"song-playlist-info\">"
		+ "<div class=\"song-playlist-song\"><%= cancion.nombre %></div>"
		+ "<div class=\"song-playlist-artist\"><%= cancion.artista.nombre %></div></div>"
		+ "</div>";

Templates.artistView = "<li data-id=\"<%= artista.codigo %>\" id=\"<%= artista.codigo %>\"  class=\"artist-view\">"
		+ "<div class=\"row\"> <div class=\"twelve columns\">"
		+ "<img class=\"artist-cover\" src=\"<%= artista.imagen_src %>\"/>"
		+ "</div>"
		+ "</div>"
		+ "<div class=\"row\">"
		+ "<div class=\"twelve columns\">"
		+ "<h3 class=\"artist-title\"> <%= artista.nombre %> </h3>"
		+ "</div>"
		+ "</div>"
		+ "<div class=\"row\">"
		+ "<div class=\"twelve columns\">"
		+ "<p class=\"artist-descp\">  <%= artista.descripcion %> </p>"
		+ "</div>" + "</div>" + "</li>";

Templates.albumView = "<li data-id=\"<%= album.codigo %>\" id=\"<%= album.codigo %>\"  class=\"l-centered album-view\">"
		+ "<div class=\"row\"> <div class=\"twelve columns\">"
		+ "<img class=\"album-cover\" src=\"/covers/<%= album.imagen_src %>\"/>"
		+ "</div>"
		+ "</div>"
		+ "<div class=\"row\">"
		+ "<div class=\"twelve columns\">"
		+ "<a class=\"addAlbPlaylist secondary l-centered btn\" style=\" margin-bottom: 10px; width:80%;\" data-id=\"<%= album.codigo %>\"><i style=\"color: #f7f7f7;\" class=\"icon-plus\" /></a>"
		+ "</div>"
		+ "</div>"
		+ "<div class=\"row\">"
		+ "<div class=\"twelve columns\">"
		+ "<h5 class=\"album-title\"> <%= album.nombre %> </h5>"
		+ "</div>"
		+ "</div>"
		+ "<div class=\"row\">"
		+ "<div class=\"twelve columns\">"
		+ "<p class=\"artista-title l-cetenred\">  <%= album.artista.nombre %> </p>"
		+ "</div>" + "</div>" + "</li>";

Templates.albumSongView = "<tr>"
		+ "<td> <%= cancion.artista.nombre %> </td>"
		+ "<td> <%= cancion.nombre %> </td>"
		+ "<td class=\"l-centered\"> <a href=\"#add\" class=\"addPlaylist medium success btn\" data-id=\"<%= cancion.codigo %>\">  <i style=\"color: #f7f7f7;\" class=\"icon icon-plus \" /> </a> </td>"
		+ "</tr>";

// This is bullshit, i'm sorry

Templates.albumContainerView = "<div class=\"row\">"
		+ "<div class=\"twelve columns\" id=\"album-descp-container\">"
		+ "<table id=\"album-songs-<%= album.codigo %>\" class=\"striped\">"
		+ "<thead>"
		+ "<tr>"
		+ "<th><img width=\"150px\" src=\"/covers/<%= album.imagen_src %>\"/></th>"
		+ "<td class=\"l-centered\" style=\"color: #F7F7F7; padding: 40px 0;\"><h3 style=\"color: #F7F7F7;\" class=\"l-centered\"><%= album.nombre %></h3></td>"
		+ "<td width=\"20%\" class=\"l-centered\" style=\"color: #F7F7F7; padding: 50px 0;\"><a href=\"#add\" class=\"addAlbPlaylist medium secondary btn\" data-id=\"<%= album.codigo %>\">  <i style=\"color: #f7f7f7;\" class=\"icon icon-plus \" /> </a></td>"
		+ "</tr>" + "</thead>" + "</table>" + "</div>" + "</div>";

// Genero {{{
Templates.generoView = "<li data-id=\"<%= genero.codigo %>\" id=\"<%= genero.codigo %>\"  class=\"genero-view\">"
		+ "<div class=\"row\"> <div class=\"twelve columns\">"
		+ "<img class=\"genero-cover\" src=\"<%= genero.imagen_src %>\"/>"
		+ "</div>"
		+ "</div>"
		+ "<div class=\"row\">"
		+ "<div class=\"twelve columns\">"
		+ "<h3 class=\"genero-title\"> <%= genero.nombre %> </h3>"
		+ "</div>"
		+ "</div>"
		+ "<div class=\"row\">"
		+ "<div class=\"twelve columns\">"
		+ "<p class=\"genero-descp\" style=\"height: 50px; overflow: hidden;\">  <%= genero.descripcion %> </p>"
// }}}

Templates.usuarioForm = "<form id=\"nusrform\" action=\"/usuarios/nusuario\" method=\"POST\">"
		+ "<fieldset>"
		+ "<legend> Agregar Usuario </legend>"
		+ "<div id=\"errors\"></div>"
		+ "<ul>"
		+ "<li class=\"l-centered prepend field\"><span class=\"adjoined\""
		+ "style=\"width: 150px;\">Usuario:</span> <input id=\"usuario\" name=\"usuario\""
		+ "class=\"xwide text input\" type=\"text\" placeholder=\"usuario\" /></li>"
		+ "<li class=\"l-centered prepend field\"><span class=\"adjoined\""
		+ "style=\"width: 150px;\">Contraseña: </span> <input id=\"password\" name=\"password\""
		+ "class=\"xwide text input\" type=\"password\" placeholder=\"contraseña\" /></li>"
		+ "<li class=\"l-centered prepend field\"><span class=\"adjoined\""
		+ "style=\"width: 150px;\">Correo:</span> <input id=\"correo\" name=\"correo\""
		+ "class=\"xwide text input\" type=\"text\""
		+ "placeholder=\"correo@domain.com\" /></li>"
		+ "<li class=\"l-centered prepend field\"><span class=\"adjoined\""
		+ "style=\"width: 150px;\">Nombres:</span> <input id=\"nombre\" name=\"nombre\""
		+ "class=\"xwide text input\" type=\"text\" placeholder=\"Nombre...\" /></li>"
		+ "<li class=\"l-centered prepend field\"><span class=\"adjoined\""
		+ "style=\"width: 150px;\">Apellidos:</span> <input id=\"apellidos\" name=\"apellidos\""
		+ "class=\"xwide text input\" type=\"text\" placeholder=\"apellidos...\" /></li>"
		+ "<li class=\"l-centered prepend field\"><span class=\"adjoined\""
		+ "style=\"width: 150px;\">Telefono:</span> <input id=\"telefono\" name=\"telefono\""
		+ "class=\"xwide text input\" type=\"text\" placeholder=\"telefono...\" /></li>"
		+ "<li class=\"l-centered\"><input type=\"submit\" value=\"Ingresar\""
		+ "style=\"height: 35px; color: #F7F7F7; width: 80%\""
		+ "class=\"info btn l-centered\"></input></li>" + "</ul>"
		+ "</fieldset>" + "</form>";

Templates.usuariosContainer = "<table id=\"users-table\">" + "<thead>" + "<tr>"
		+ "<th>Usuario</th>" + "<th>Nombre</th>" + "<th>Apellidos</th>"
		+ "<th>Telefono</th>" + "<th>Correo</th>" + "<th></th>" + "</tr>"
		+ "</thead>" + "</table>";

Templates.usuarioDetailView = "<tr>" + "<td> <%= usuario.usuario %> </td>"
		+ "<td> <%= usuario.nombre %> </td>"
		+ "<td> <%= usuario.apellidos %> </td>"
		+ "<td> <%= usuario.telefono %> </td>"
		+ "<td> <%= usuario.email %> </td>" + "</tr>";